-- 즐겨찾기가 가장 많은 식당 정보 출력하기 group by, sub query

-- 내가 짰던 틀린 코드
-- 레스토랑 명이 일치하지 않게 됨
-- SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES)
-- FROM REST_INFO
-- GROUP BY FOOD_TYPE
-- ORDER BY FOOD_TYPE DESC;


-- 윈도우함수 활용
-- SELECT FOOD_TYPE
--      , REST_ID
--      , REST_NAME
--      , FAVORITES
--  FROM (
--         SELECT FOOD_TYPE
--              , REST_ID
--              , ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
--              , FAVORITES
--              , REST_NAME
--           FROM REST_INFO
--       ) AS SUBQUERY
-- WHERE RN = 1
-- ORDER BY FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN
       (SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC